import { useState } from 'react'

export default function TerraformOutput({ plan }) {
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState('terragrunt') // 'terragrunt' or 'terraform'

  if (!plan || !plan.allocations) return null

  const hub = plan.allocations.find(a => a.type === 'hub')
  const spokes = plan.allocations.filter(a => a.type === 'spoke')

  const generateTerragrunt = () => {
    let output = `# Hub VNet Configuration
# Generated by HeliosCrypt CIDR Planner

inputs = {
  # Hub Virtual Network
  hub_vnet_name          = "vnet-hub-001"
  hub_vnet_address_space = ["${hub?.cidr || '10.0.0.0/22'}"]

  hub_subnets = [
${hub?.subnets.map(s => `    {
      name           = "${s.name}"
      address_prefix = "${s.cidr}"
    }`).join(',\n') || ''}
  ]

  # Spoke Virtual Networks
  spokes = [
${spokes.map(spoke => `    {
      name          = "${spoke.name}"
      address_space = ["${spoke.cidr}"]
      subnets = [
${spoke.subnets.map(s => `        {
          name           = "${s.name}"
          address_prefix = "${s.cidr}"
        }`).join(',\n')}
      ]
    }`).join(',\n')}
  ]
}

# Growth Reserved CIDRs (for documentation)
# ${plan.growthReserved.join(', ') || 'None'}`

    return output
  }

  const generateTerraform = () => {
    let output = `# Hub VNet Configuration
# Generated by HeliosCrypt CIDR Planner

locals {
  hub_address_space = ["${hub?.cidr || '10.0.0.0/22'}"]

  hub_subnets = {
${hub?.subnets.map(s => `    ${s.name} = {
      address_prefix = "${s.cidr}"
    }`).join('\n') || ''}
  }

  spokes = {
${spokes.map(spoke => `    "${spoke.name}" = {
      address_space = ["${spoke.cidr}"]
      subnets = {
${spoke.subnets.map(s => `        ${s.name} = {
          address_prefix = "${s.cidr}"
        }`).join('\n')}
      }
    }`).join('\n')}
  }

  # Growth Reserved CIDRs
  reserved_cidrs = [
${plan.growthReserved.map(c => `    "${c}"`).join(',\n') || '    # None'}
  ]
}`

    return output
  }

  const output = format === 'terragrunt' ? generateTerragrunt() : generateTerraform()

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setFormat('terragrunt')}
            className={`px-3 py-1 text-sm rounded-lg transition-colors ${
              format === 'terragrunt'
                ? 'bg-helio-600 text-white'
                : 'bg-dark-900 text-gray-400 hover:text-white'
            }`}
          >
            Terragrunt
          </button>
          <button
            onClick={() => setFormat('terraform')}
            className={`px-3 py-1 text-sm rounded-lg transition-colors ${
              format === 'terraform'
                ? 'bg-helio-600 text-white'
                : 'bg-dark-900 text-gray-400 hover:text-white'
            }`}
          >
            Terraform
          </button>
        </div>
        <button
          onClick={copyToClipboard}
          className="flex items-center gap-2 px-4 py-2 bg-helio-600 hover:bg-helio-500 text-white text-sm font-medium rounded-lg transition-colors"
        >
          {copied ? (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Copy
            </>
          )}
        </button>
      </div>

      <div className="bg-[#1e1e1e] rounded-xl overflow-hidden">
        <pre className="p-4 text-sm font-mono overflow-x-auto max-h-[500px] overflow-y-auto">
          <code className="text-gray-300">{output}</code>
        </pre>
      </div>

      <p className="text-xs text-gray-500">
        Note: Review and adjust the generated configuration to match your naming conventions and requirements.
      </p>
    </div>
  )
}
